name: Lunar Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: 0xWelt/Lunar@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional, change as you wish or comment out to use default
          OPENAI_BASE_URL: https://api.deepseek.com/v1 # https://api.openai.com/v1
          MODEL: deepseek-chat # gpt-4o-mini
          LANGUAGE: Chinese # Chinese
          TEMPERATURE: 1.0 # 1.0
          MAX_TOKENS: 8192 # 4096
